-- graph.lua

local ls = require 'luasnip'

local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s('topo', {
    t {
      '// Khans Algorithm',
      'vll topo_sort(ll n, vvll& adj){',
      '    vll indeg(n, 0);',
      '',
      '    for(ll node = 0; node < n; node++){',
      '        for(ll neigh : adj[node]){',
      '            indeg[neigh]++;',
      '        }',
      '    }',
      '',
      '    queue<ll> q;',
      '',
      '    for(ll i = 0; i < n; i++){',
      '        if(indeg[i] == 0)',
      '            q.push(i);',
      '    }',
      '',
      '    vll topo;',
      '',
      '    while(!q.empty()){',
      '        ll node = q.front();',
      '        q.pop();',
      '',
      '        topo.pb(node);',
      '',
      '        for(ll neigh : adj[node]){',
      '            indeg[neigh]--;',
      '',
      '            if(indeg[neigh] == 0){',
      '                q.push(neigh);',
      '            }',
      '        }',
      '    }',
      '',
      '    return topo;',
      '}',
    },
  }),

  s('kruskal', {
    t {
      'struct Edge {',
      '    ll u, v, w;',
      '',
      '    bool operator<(const Edge &other) const {',
      '        return w < other.w;',
      '    }',
      '};',
      '',
      '// Kruskals Algorithm',
      'vector<Edge> kruskal(ll n, vector<Edge> &edges){',
      '    sort(all(edges));',
      '',
      '    DSU dsu(n);',
      '    vector<Edge> mst;',
      '',
      '    for(auto &e : edges){',
      '        if(dsu.find(e.u) != dsu.find(e.v)){',
      '            dsu.unite(e.u, e.v);',
      '            mst.pb(e);',
      '',
      '            if(len(mst) == n - 1)',
      '                break;',
      '        }',
      '    }',
      '',
      '    return mst;',
      '}',
    },
  }),

  s('dij', {
    t {
      '// Dijkstra',
      'vll dijkstra(ll src, vector<vpll> &adj){',
      '    ll n = len(adj);',
      '',
      '    vll dist(n, INF);',
      '    minpq<pll> pq;',
      '',
      '    dist[src] = 0;',
      '    pq.push({0, src});',
      '',
      '    while(!pq.empty()){',
      '        auto [d, u] = pq.top();',
      '        pq.pop();',
      '',
      '        if(d > dist[u])',
      '            continue;',
      '',
      '        for(auto &[v, w] : adj[u]){',
      '            if(dist[u] + w < dist[v]){',
      '                dist[v] = dist[u] + w;',
      '                pq.push({dist[v], v});',
      '            }',
      '        }',
      '    }',
      '',
      '    return dist;',
      '}',
    },
  }),
}
