-- templates.lua

local ls = require 'luasnip'
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s('bruh', {
    t {
      '#include <bits/stdc++.h>',
      'using namespace std;',
      '',
      'using ll = long long;',
      'using vll = vector<ll>;',
      '#define rep(i,a,b) for(ll i=(a); i<(b); i++)',
      '#define all(x) (x).begin(), (x).end()',
      '#define rall(x) (x).rbegin(), (x).rend()',
      '#define fastio ios::sync_with_stdio(false); cin.tie(nullptr);',
      'const ll MOD = 1e9+7;',
      '',
      'll mpow(ll a, ll b, ll mod = MOD){',
      '    ll res = 1;',
      '    a %= mod;',
      '',
      '    while(b){',
      '        if(b & 1) res = res * a % mod;',
      '        a = a * a % mod;',
      '        b >>= 1;',
      '    }',
      '',
      '    return res;',
      '}',
      '',
      'll inv(ll x){',
      '    return mpow(x, MOD - 2);',
      '}',
      '',
      'void solve(){',
      '    ',
    },
    i(1),
    t {
      '',
      '}',
      '',
      'int main(){',
      'fastio;',
      '    int t = 1;',
      '    cin >> t;',
      '    while (t--) solve();',
      '',
      '    return 0;',
      '}',
    },
  }),

  -- cf (Codeforces template with solve() + test cases)
  s('cf', {
    t {
      '#include <bits/stdc++.h>',
      'using namespace std;',
      '',
      '// Macros',
      'using ll = long long;',
      'using ld = long double;',
      'using str = string;',
      '',
      'using pll = pair<ll,ll>;',
      'using vs = vector<string>;',
      'using vi = vector<int>;',
      'using vll = vector<ll>;',
      'using vvll = vector<vll>;',
      'using vpll = vector<pll>;',
      '',
      'template<typename T>',
      'using minpq = priority_queue<T, vector<T>, greater<T>>;',
      'template<typename T>',
      'using maxpq = priority_queue<T>;',
      '',
      '#define len(x) (ll)(x).size()',
      '#define pb push_back',
      '#define ff first',
      '#define ss second',
      '',
      '#define fastio ios::sync_with_stdio(false); cin.tie(nullptr);',
      '#define all(x) (x).begin(), (x).end()',
      '#define rall(x) (x).rbegin(), (x).rend()',
      '#define rep(i,a,b) for(ll i=(a); i<(b); i++)',
      '',
      'const ll INF = 1e18;',
      'const ll MOD = 1e9+7;',
      '//const ll MOD = 998244353;',
      '',
      '// Debug Template',
      '#ifndef ONLINE_JUDGE',
      '#define debug(x) cerr << #x << " = "; _print(x); cerr << endl;',
      '#else',
      '#define debug(x)',
      '#endif',
      '',
      'void _print(ll x) { cerr << x; }',
      'void _print(string x) { cerr << x; }',
      '',
      'template <class T>',
      'void _print(const vector<T>& v) {',
      '    cerr << "[ ";',
      '    for (int i = 0; i < (int)v.size(); i++) {',
      '        _print(v[i]);',
      '        if (i != (int)v.size() - 1) cerr << ", ";',
      '    }',
      '    cerr << " ]";',
      '}',
      '',
      'vll dx = {1, -1, 0, 0, 1, 1, -1, -1};',
      'vll dy = {0, 0, 1, -1, 1, -1, 1, -1};',
      'str DIR = "DURL";',
      '',
      'void solve(){',
      '    ',
    },
    i(1),
    t {
      '',
      '}',
      '',
      'int main(){',
      '    fastio;',
      '',
      '    int t = 1;',
      '    cin >> t;',
      '    while (t--) solve();',
      '',
      '    return 0;',
      '}',
    },
    i(0),
  }),
}
