-- trees.lua

local ls = require 'luasnip'

local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s('segtree', {
    t {
      '// Segment Tree',
      'class SegmentTree {',
      'private:',
      '    ll n;',
      '    vll tree;',
      '',
      '    ll merge(ll l, ll r){',
      '    }',
      '',
      '    ll neutral(){',
      '    }',
      '',
      '    void build(ll node, ll l, ll r, vll &arr){',
      '        if(l == r){',
      '            tree[node] = arr[l];',
      '            return;',
      '        }',
      '',
      '        ll mid = (l + r) / 2;',
      '',
      '        build(2 * node + 1, l, mid, arr);',
      '        build(2 * node + 2, mid + 1, r, arr);',
      '',
      '        tree[node] = merge(tree[2 * node + 1], tree[2 * node + 2]);',
      '    }',
      '',
      '    ll query(ll node, ll l, ll r, ll ql, ll qr){',
      '        if(qr < l || r < ql)',
      '            return neutral();',
      '',
      '        if(ql <= l && r <= qr)',
      '            return tree[node];',
      '',
      '        ll mid = (l + r) / 2;',
      '',
      '        return merge(',
      '            query(2 * node + 1, l, mid, ql, qr),',
      '            query(2 * node + 2, mid + 1, r, ql, qr)',
      '        );',
      '    }',
      '',
      '    void update(ll node, ll l, ll r, ll idx, ll val){',
      '        if(l == r){',
      '            tree[node] = val;',
      '            return;',
      '        }',
      '',
      '        ll mid = (l + r) / 2;',
      '',
      '        if(idx <= mid)',
      '            update(2 * node + 1, l, mid, idx, val);',
      '        else',
      '            update(2 * node + 2, mid + 1, r, idx, val);',
      '',
      '        tree[node] = merge(tree[2 * node + 1], tree[2 * node + 2]);',
      '    }',
      '',
      'public:',
      '    SegmentTree(vll &arr){',
      '        n = len(arr);',
      '        tree.resize(4 * n);',
      '',
      '        build(0, 0, n - 1, arr);',
      '    }',
      '',
      '    ll query(ll l, ll r){',
      '        return query(0, 0, n - 1, l, r);',
      '    }',
      '',
      '    void update(ll idx, ll val){',
      '        update(0, 0, n - 1, idx, val);',
      '    }',
      '};',
    },
  }),

  s('lazysegtree', {
    t {
      'class LazySegmentTree {',
      'private:',
      '    ll n;',
      '    vll tree, lazy;',
      '',
      '    ll merge(ll left, ll right){',
      '    }',
      '',
      '    ll neutral(){',
      '    }',
      '',
      '    void apply(ll node, ll l, ll r, ll val){',
      '    }',
      '',
      '    void build(ll node, ll l, ll r, vll &arr){',
      '        if(l == r){',
      '            tree[node] = arr[l];',
      '            return;',
      '        }',
      '',
      '        ll mid = (l + r) / 2;',
      '',
      '        build(2 * node + 1, l, mid, arr);',
      '        build(2 * node + 2, mid + 1, r, arr);',
      '',
      '        tree[node] = merge(tree[2 * node + 1], tree[2 * node + 2]);',
      '    }',
      '',
      '    void push(ll node, ll l, ll r){',
      '        if(lazy[node] == 0)',
      '            return;',
      '',
      '        apply(node, l, r, lazy[node]);',
      '',
      '        if(l != r){',
      '            lazy[2 * node + 1] += lazy[node];',
      '            lazy[2 * node + 2] += lazy[node];',
      '        }',
      '',
      '        lazy[node] = 0;',
      '    }',
      '',
      '    void update(ll node, ll l, ll r, ll ql, ll qr, ll val){',
      '        push(node, l, r);',
      '',
      '        if(qr < l || r < ql)',
      '            return;',
      '',
      '        if(ql <= l && r <= qr){',
      '            apply(node, l, r, val);',
      '',
      '            if(l != r){',
      '                lazy[2 * node + 1] += val;',
      '                lazy[2 * node + 2] += val;',
      '            }',
      '',
      '            return;',
      '        }',
      '',
      '        ll mid = (l + r) / 2;',
      '',
      '        update(2 * node + 1, l, mid, ql, qr, val);',
      '        update(2 * node + 2, mid + 1, r, ql, qr, val);',
      '',
      '        tree[node] = merge(tree[2 * node + 1], tree[2 * node + 2]);',
      '    }',
      '',
      '    ll query(ll node, ll l, ll r, ll ql, ll qr){',
      '        push(node, l, r);',
      '',
      '        if(qr < l || r < ql)',
      '            return neutral();',
      '',
      '        if(ql <= l && r <= qr)',
      '            return tree[node];',
      '',
      '        ll mid = (l + r) / 2;',
      '',
      '        return merge(',
      '            query(2 * node + 1, l, mid, ql, qr),',
      '            query(2 * node + 2, mid + 1, r, ql, qr)',
      '        );',
      '    }',
      '',
      'public:',
      '    LazySegmentTree(vll &arr){',
      '        n = len(arr);',
      '        tree.resize(4 * n);',
      '        lazy.resize(4 * n, 0);',
      '',
      '        build(0, 0, n - 1, arr);',
      '    }',
      '',
      '    void update(ll l, ll r, ll val){',
      '        update(0, 0, n - 1, l, r, val);',
      '    }',
      '',
      '    ll query(ll l, ll r){',
      '        return query(0, 0, n - 1, l, r);',
      '    }',
      '};',
    },
  }),
}
